### PR TITLE
Parallel

### PR DESCRIPTION
**Pull request by haf**

### CODE REVIEW

**Comment by haf** [comment]
Left for me: assert.fs

I don't want to spend much time on Runners since I'm not using it. Will work a few more hours on this, then I want to start using it, with or without runners.

**Comment by haf** [comment]
I think this is ready to test now. I had to organise all the global variables in their own modules so the basic tests has a few more opens now. Also, the "classic mode" overrides the bitwise and operator and provides no way to avoid doing precisely that, which isn't very good.

**Comment by lefthandedgoat** [comment]
Sounds great.  I have a very early flight tomorrow so I won't be able to spend any time on it tonight.  I will work on it during the week, since I am stuck in a hotel.

**Comment by lefthandedgoat** [comment]
Its gonna be a while to work through this, there are currently 115+ build errors to work through.

**Comment by haf** [comment]
@lefthandedgoat Not AFAIK - there were no build errors when I pushed the latest

**Comment by haf** [comment]
I missed a push... Darn

**Pull request merged**
