### PR TITLE
#461 Changed build script to use fake instead of fsi for docs generation

### PR DESCRIPTION
**Pull request by JeremyBellows**
Thank you to the wonderful people of F# for leaving a bread crumb trail

https://github.com/fsprojects/ProjectScaffold/commit/6e4a6b63a8d6e63a1c89733bb69a2150ebf0deaf#diff-2efaaa9f2632e3258cdcbc80f78883eaR186

https://github.com/fsharp/FAKE/issues/1092

### CODE REVIEW

**Comment by JeremyBellows** [comment]
@lefthandedgoat It was ignoring the exit code before. Do we want to continue ignoring the exit code of the script?

**Comment by JeremyBellows** [comment]
Not ready yet. found a bug. Investigating

**Comment by JeremyBellows** [comment]
A big future project:

Migrate FAKE scripts to FAKE 5 (fully support Dotnet core)

https://fake.build/fake-migrate-to-fake-5.html

Potential Obstacles
- Razor https://github.com/fsprojects/FSharp.Formatting/issues/494
- Backwards dev compatibility

Pros
- Reduce dependencies and group them
- Added FAKE functions that simplify the code
- Fake integration with dotnet CLI

Ideas
- Integrate canopy into the dotnet cli test runner

**Comment by JeremyBellows** [comment]
Current Issues
- " Could not read comments from entity 'canopy.reporters.LiveHtmlReporter': System.InvalidOperationException: The entity or value 'System.Exception' does not exist or is in an unresolved assembly. You may need to add a reference to assembly 'netstandard'"
- "Could not read comments from entity 'classic': Microsoft.FSharp.Compiler.ErrorLogger+UnresolvedPathReferenceNoRange: Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+UnresolvedPathReferenceNoRange' was thrown."
- "FSharp.Formatting Error: 0 : Error while building member-name for canopy.types.Test because: not a named type"
- "Could not read comments from entity 'canopy.csharp.canopy': System.InvalidOperationException: The entity or value 'OpenQA.Selenium.By' does not exist or is in an unresolved assembly. You may need to add a reference to assembly 'WebDriver'"

**Comment by thinkbeforecoding** [comment]
@JeremyBellows in [FSharp.Text.RegexProvider](https://github.com/fsprojects/FSharp.Text.RegexProvider/blob/master/docs/tools/generate.fsx) I updated the doc generation to not use Razor, but Fable.React server side rendering...

**Comment by lefthandedgoat** [comment]
Thanks a mil Jeremy!

**Comment by lefthandedgoat** [comment]
Jeremy if you have the willpower to look into this, errors were thrown during the reference generation and it looks like some pages are not there (classic, parallell, and instanced looks broke)

http://lefthandedgoat.github.io/canopy/reference/index.html

Also, all the paths on the right hand list of links like Actions etc, are pointed at c://my/path/to/canopy

http://lefthandedgoat.github.io/canopy/index.html

**Comment by JeremyBellows** [comment]
I think it's time to start the big project mentioned above.

We need to migrate FAKE to FAKE 5.0 

Much thanks to @thinkbeforecoding for removing Razor! That was a huge obstacle.

@lefthandedgoat If we follow the [migration docs](https://fake.build/fake-migrate-to-fake-5.html) in order then it will hopefully be not as painful.

Another option is recreating canopy with a blank dotnet core template. I'm not confident yet that this is a less painful route.

What do you want to do?

**Comment by lefthandedgoat** [comment]
@JeremyBellows  Fake 5 is fine with me.  If we remove the two deprecated Nuget targes, the script is less than 200 lines long which seems manageable?

**Comment by lefthandedgoat** [comment]
@JeremyBellows I have updated to Fake5 except for what I think are a few new helpers you added earlier.

https://github.com/lefthandedgoat/canopy/tree/484-fix-documentation

Does that put it in a good place for you?

**Pull request merged**
