### PR TITLE
at - Added a function to ctrlClick for times when you perhaps want to…

### PR DESCRIPTION
**Pull request by ataylorm**
… select multiple items in a list box.

### CODE REVIEW

**Comment by lefthandedgoat** [comment]
Awesome thanks!  I will get it this pulled in this weekend and release a new build.

**Comment by ataylorm** [comment]
Cool,

I thought about making it more of a holdClick key element type deal so you could also do it for Alt, Shift, etc.  What are your thoughts?  ctrlClick seems to be the most common, but figured I would ask you thoughts.

p.s.  What type of food sounds good for lunch?

Sincerely,
Andrew Taylor


GameStop | Andrew Taylor | Advanced Engineer - eCommerce  | (817) 722-7285 Office | (469) 263-3798 Cell | Skype (ataylorm) | 625 Westport Parkway, Grapevine, TX 76051 |  Powertotheplayers!

**Comment by lefthandedgoat** [comment]
For now the specific one for ctrl is fine.  As more are needed we can add them and as we see a pattern create the right abstraction.

For lunch I am easy no real preference.

**Comment by lefthandedgoat** [comment]
You can download this now!

https://www.nuget.org/packages/canopy/0.9.46

Thanks again for your contribution!

**Pull request merged**
