### PR TITLE
added action: positionBrowser

### PR DESCRIPTION
**Pull request by navmed**
I hope I'm not getting ahead of myself - I needed this functionality, I thought I'd add it myself and contribute. Feel free to tweak as needed.

### CODE REVIEW

**Comment by lefthandedgoat** [comment]
I will try to test it and get it in a build tonight

**Comment by navmed** [comment]
Awesome!

**Comment by navmed** [comment]
Let me know if you have any concerns or need changes on this.

**Comment by lefthandedgoat** [comment]
Sorry I just havent done it. Today I will, guarantee.

**Comment by lefthandedgoat** [comment]
Thank you for the contribution.  You can download here:

https://www.nuget.org/packages/canopy/0.9.59

**Comment by navmed** [comment]
Awesome!

**Pull request merged**
