### PR TITLE
Fix GenerateDocs

### PR DESCRIPTION
**Pull request by sergey-tihon**
@lefthandedgoat There is a better way // cc @forki 
https://github.com/lefthandedgoat/canopy/commit/4953ca649fe74837368ae8fa5b19a48cd1d19f00#commitcomment-16664727

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@lefthandedgoat 
BTW, Is there any reason why you use Newtonsoft.Json `6.0` instead of `8.0`?

**Comment by lefthandedgoat** [comment]
Cool that worked!
@sergey-tihon  Yes because (and I havent tested it recently) version 7.0 broke Jquery selectors like `:visible`

8.0 may work, I can try it.  Otherwise I have to ask the guy who made SizzleCss package to update and deploy also.

**Comment by sergey-tihon** [comment]
You always can easily check for new versions
`.paket\paket.exe outdated`
and update any package
`.paket\paket.exe update nuget PackageName`

image

**Comment by lefthandedgoat** [comment]
```
"#welcome should have Welcome" &&& fun _ ->    
    url testpage
    "#welcome:visible" == "Welcome"
```

That test with `:visible' will fail with Json.Net v8

**Comment by lefthandedgoat** [comment]
Opened an issue here: https://github.com/fschwiet/SizSelCsZzz/issues/7

**Pull request merged**
