### PR TITLE
Parallel

### PR DESCRIPTION
**Pull request by haf**

### CODE REVIEW

**Comment by haf** [comment]
I would appreciate if you don't throw away my commit history when you merge; it causes lots and lots of merge errors for me and we're merging into a specific branch anyway, which you can squash when you merge it into master. So please, just merge it, don't squash it.

**Comment by lefthandedgoat** [comment]
I just push the button.  They've changed the default to Squash and merge.  I will be more careful.

**Comment by haf** [comment]
The PR compiles; you can merge it as is if you want, by reverting your previous commit first, I think...

**Comment by lefthandedgoat** [comment]
I still get a huge number of build errors.

image


I want Parallel support also, so I am going to continue the effort I had started a long time ago and see where that leads.

**Comment by haf** [comment]
This branch **does** compile. If you'd please set up Travis I can prove it to you.

Also, the **waiting** branch is not ready to be merged, that was a separate PR.

I can only assume the above screenshot is not of the **waiting** branch.

**Comment by haf** [comment]
Please take this the right way; I'll ensure my PR works, you don't have to... This is my main point.

If you'd enable Travis I can ensure they work without you having to download the code and try to compile it, which would free up your time and make it easier for me to work with this repository.

Also, you may want to consider not merging straight away; [since the PR is linked to a specific branch, you can push to the same branch I PR **from**](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/). That way we don't run into merge conflicts and we can cooperate better.

Also, on the same note, unless I state a PR ready to be merged or worked on, it's probably not. Sorry about confusion there.

**Comment by lefthandedgoat** [comment]
I get similar errors on with or without the Waiting branch.  I only accepted it because I thought maybe it would have fewer errors.

No wait:

image

With with:

image

I will work on getting travis setup today.  Unfortunately, even if it builds on Travis, it doesn't build on my machine, and if it doesn't build on my machine I can't contribute to my own project which is obviously a problem.

"Also, parallel support is complete, so it's a bit absurd that you're saying you're going to continue your old work after all the days I've spent on this."

I don't want to throw any work away.  Me working on the same problem but on a different branch lets me flush out ideas I have also.

**Comment by haf** [comment]
The Logging errors is from not running `./build.sh`.

**Comment by lefthandedgoat** [comment]
I am on windows, and I did run build.cmd.

Here are the travis reports: https://travis-ci.org/lefthandedgoat/canopy/builds/353120735

**Comment by lefthandedgoat** [comment]
I have most things building on windows now.

**Comment by lefthandedgoat** [comment]
I have everything building now, but basictests fail here:

https://github.com/lefthandedgoat/canopy/blob/AddSupportForParallelWithHaf/src/Canopy/Canopy.fs#L125-L128

I tried using this method to set the _globalcontext with no luck:

https://github.com/lefthandedgoat/canopy/blob/AddSupportForParallelWithHaf/src/Canopy/Canopy.fs#L104

**Comment by haf** [comment]
I’ll try it out. Are all things failing or just one test? How are you running it, what command line, and what browser?

--

**Comment by lefthandedgoat** [comment]
Get latest on this branch and from OSX run `sh build.sh` and it should fail with this error

```
Unhandled Exception:
System.InvalidOperationException: No global context configured yet
  at Canopy.Core+ContextModule.getContext () [0x00054] in <5aaf235cd45c0b6da74503835c23af5a>:0 
  at Canopy.Core+ContextModule.mutateNoLock[us] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] callback) [0x00001] in <5aaf235cd45c0b6da74503835c23af5a>:0 
  at Canopy.Core+ContextModule.mutate[us] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] callback) [0x0000f] in <5aaf235cd45c0b6da74503835c23af5a>:0 
  at Canopy.Core.startWithConfig (Canopy.CanopyConfig config, Canopy.Types+BrowserStartMode mode) [0x0000f] in <5aaf235cd45c0b6da74503835c23af5a>:0 
  at <StartupCode$basictests>.$main.main@ () [0x00102] in <5aaf23601c4dc10ea74503836023af5a>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: No global context configured yet
  at Canopy.Core+ContextModule.getContext () [0x00054] in <5aaf235cd45c0b6da74503835c23af5a>:0 
  at Canopy.Core+ContextModule.mutateNoLock[us] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] callback) [0x00001] in <5aaf235cd45c0b6da74503835c23af5a>:0 
  at Canopy.Core+ContextModule.mutate[us] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] callback) [0x0000f] in <5aaf235cd45c0b6da74503835c23af5a>:0 
  at Canopy.Core.startWithConfig (Canopy.CanopyConfig config, Canopy.Types+BrowserStartMode mode) [0x0000f] in <5aaf235cd45c0b6da74503835c23af5a>:0 
  at <StartupCode$basictests>.$main.main@ () [0x00102] in <5aaf23601c4dc10ea74503836023af5a>:0 

```

**Comment by amirrajan** [comment]
@haf I've been following this pull request. It _really_ concerns me that all these changes were made without running the test suite. Is there any way we can maybe split this pull request up into smaller/more focused pull requests?

**Comment by haf** [comment]
@amirrajan No

**Comment by amirrajan** [comment]
>Why didn't you send the PR in the first case? Or help out while I was working on it?

Don't have a need for parallel at the framework level (I use separate processes to control parallelization). Hope you get the full test suite running w/o failures 👍

**Comment by haf** [comment]
@amirrajan Thanks

**Pull request merged**
