### PR TITLE
Added support for Safari, changes required to  run canopy on OSX and Linux(mono)

### PR DESCRIPTION
**Pull request by pedro-ramirez-suarez**
- Added Safari to the supported browsers
- Different paths for the browser's driver depending on the OS

Tested changes on Windows(Chrome, IE, FireFox and Safari), Linux(Firefox and Chrome), OSX(Safari, Firefox, Chrome)

### CODE REVIEW

**Comment by pedro-ramirez-suarez** [comment]
We needed to run automated tests on Safari for OSX, so I made small changes to support that.

There is a small trick to test Safari on OSX, to run tests on Safari, you need to have the Chrome Driver and the file name must be "chromedriver.exe", by default the Chrome driver for OSX does not have the ".exe" extension so you need to add it.

**Comment by lefthandedgoat** [comment]
Nice, I actually develop on OSX and use the same chromedriver.exe trick.  I will accept and make some minor changes.  I will try to get a new build out for you tonight.  Thanks!

**Comment by pedro-ramirez-suarez** [comment]
Great!, thanks to you

**Comment by lefthandedgoat** [comment]
Available for download here:

https://www.nuget.org/packages/canopy/0.9.32

Thanks again!

**Pull request merged**
