### PR TITLE
[WIP] support .net standard

### PR DESCRIPTION
**Pull request by enricosada**
this add .net standard 2..0 in parallel to existing (so less problem ihmo), and will merge `netstandard2.0` built assembly in the usual package

@lefthandedgoat  some open questions:

- atm doing `build Build` fails for me (`Rebuild target not found`)
- `dotnet build` with .net core sdk crash `fsc` with stackoverflow, oops ( https://github.com/Microsoft/visualfsharp/issues/3696 )
  - crash is related to `FSharp.Data` usage, is really needed?
- what's the best way to run all tests?
- want a travis/appveyor to run test/create package?

NOTES

- for screen info, use the same default like when running on mono

TODO

- [ ] merge netstandard in currrent package
- [ ] fix or workround dotnet build error

### CODE REVIEW

**Comment by enricosada** [comment]
current status:

- restore with `dotnet restore`
- build is with `msbuild tests\basictests.netcore\basictests.netcore.fsproj /t:Build` (msbuild 15.3 => vs2017 15.3)
- 1 of `tests/basictests.netcore` tests fails

canopy

**Comment by lefthandedgoat** [comment]
Interesting, I didn't think .netcore would work because canopy is a wrapper to selenium which does not have a .netcore version!

`atm doing build Build fails for me (Rebuild target not found)`
I use 'rake' command and run things from a rake task, there is a build fake script but I generally just use the 'Release' task which does a build and creates a nuget package

`dotnet build with .net core sdk crash fsc with stackoverflow, oops`
I dont know to be honest, I know so little about .netcore

`crash is related to FSharp.Data usage, is really needed?`
FSharp.Data is used for a feature to build an AST of Json and validate it.  Its a different project and technically I could pull the source into its own solution if its really a problem.

`what's the best way to run all tests?`
'rake' from command line if you have rake installed

`want a travis/appveyor to run test/create package?`
I do it manually now because I only do it like one per month or something, and often merge multiple things in before doing a build.  I am ok with doing it manually going forward also, just because I am weird.

**Comment by enricosada** [comment]
with new [Selenium.WebDriver v3.6.0](https://www.nuget.org/packages/Selenium.WebDriver/3.6.0) now netstandard2.0 is supported (9days ago)

@lefthandedgoat i tried to do this PR at openfsharp conf, but zero time :(

> I use 'rake' command and run things from a rake task, there is a build fake script but I generally just use the 'Release' task which does a build and creates a nuget package

ok for rake, but the `build.fsx` specify old VS 11 (vs 2012), can i upgrade that? i have just 2013-2017 installed. anyone is ok

> dotnet build with .net core sdk crash fsc with stackoverflow, oops
> I dont know to be honest, I know so little about .netcore

np, already reported that in https://github.com/Microsoft/visualfsharp/issues/3696 . doesnt matter atm

> crash is related to FSharp.Data usage, is really needed?
> FSharp.Data is used for a feature to build an AST of Json and validate it. Its a different project and technically I could pull the source into its own solution if its really a problem.

I'll pull source so, as workaround for now.

ok rake, no appveyor/travis. np, less work :D

**Comment by lefthandedgoat** [comment]
Didnt realize there was a nice version, nice!

Yes you can upgrade to a new version of VS, 2015 sounds good.

For Fsharp.Data I really don't have a problem creating a sub solution and remove it from the main canopy solution.  I am pretty confident the code is stand alone.  Its related to Integration testing, not UI testing, but I figured I would make it a part of the 'canopy brand'.

**Comment by lefthandedgoat** [comment]
I've completed canopy 2.0 which has both .net standard 2.0 support and parallel support.

You can download it here: https://www.nuget.org/packages/canopy/2.0.0

You can read the upgrade documentation here: http://lefthandedgoat.github.io/canopy/upgrade1to2.html

Thanks for your work on this, I looked at your code for reference!

**Pull request closed without merging**
