### PR TITLE
reconfigured proj files to not use the package rebuild

### PR DESCRIPTION
**Pull request by fischgeek**
## Proposed Changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to canopy?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] Build and tests pass locally
- [ ] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

I couldn't get the project to build on my end and removing the Imports in the proj files fixes it and allows the packages to resolve themselves. In addition to that, I had to add System.Drawing.Common from the Package Manager. So, not sure if this is a valid PR, but I thought I'd give it a shot.

### CODE REVIEW

**Comment by lefthandedgoat** [comment]
Why stop using paket?

**Comment by fischgeek** [comment]
I think it's still using package dependencies, but those Import lines in the proj files threw build errors and removing them allowed the project to build. I don't know, I might be waiving a n00b flag here; let me know.

**Comment by lefthandedgoat** [comment]
Can you help me with steps to reproduce your build error and I will see whats happening.

**Comment by fischgeek** [comment]
Sure. 
1. Clone the canopy repo
2. Open the solution
3. Observe the Error List 

```
MSB3073	The command "dotnet paket restore" exited with code 1.	canopy
MSB3073	The command "dotnet paket restore" exited with code 1.	canopy.integration
MSB3073	The command "dotnet paket restore" exited with code 1.	csharptests
MSB3073	The command "dotnet paket restore" exited with code 1.	basictests
MSB3073	The command "dotnet paket restore" exited with code 1.	paralleltests
```
Cleaning, rebuilding or attempting to restore packages all throw the same errors. The dependencies in each project have the yellow triangle in them as well. Maybe I'm doing something wrong or missing a step?

**Comment by lefthandedgoat** [comment]
When I clone and open in VS I see the same errors.

If you run `build.cmd` from the command line it will make it build in VS correctly.  The command line build wont run correctly, something I will fix, but it will make it build in VS.  Hope this helps.

**Comment by fischgeek** [comment]
I tried to navigate to the directory in PS and run `build.cmd` but that isn't a recognized command. I also tried `dotnet build` which resulted in the same errors.

**Comment by lefthandedgoat** [comment]
Try running the commands in the build.cmd

https://github.com/lefthandedgoat/canopy/blob/master/build.cmd

**Pull request closed without merging**
