### PR TITLE
Option to select WebDriver port and allow insecure SSL cert

### PR DESCRIPTION
**Pull request by OmanF**
* Added configuration flag to specifiy port number for the WebDriver instance to listen on (instead of the default randomized one). Currently, Chrome-family ONLY!
* Added configuration flag to allow insecure SSL certs to be accepted, as without this, Chrome Headless is all but useless. Currently, Chrome-family ONLY!
* Added documentation of above mentioned changes in correct file.
* A lot of stylistic cleanup, reformatting and reflowing suggested by Fantomas formatter tool.

### CODE REVIEW

**Comment by lefthandedgoat** [comment]
I appreciate the contribution but they way it was formatted was fine in my book.

Can you re-submit with just the actual functionality?

**Comment by OmanF** [comment]
I'm not sure if I did it correctly, but I reverted the formatting changes and re-applied the functionality on my fork so, I'm guessing, it also updated the PR?
(I'm kinda new to the PR thingie).

**Comment by lefthandedgoat** [comment]
I will let you know when I get a new build out.

**Comment by OmanF** [comment]
Appreciate it. Thanks!

**Comment by lefthandedgoat** [comment]
https://www.nuget.org/packages/canopy/2.1.1

You can download the updates now, thanks again!

**Comment by OmanF** [comment]
Oh, wow! My first ever PR on a public project merged and live.

Thank you very much!

**Pull request merged**
