### PR TITLE
Parallel support, rebased on master

### PR DESCRIPTION
**Pull request by haf**
Basic tests, fixes for context.

3 minutes 25 seconds to execute
116 passed
10 skipped
15 failed

### CODE REVIEW

**Comment by haf** [comment]
Can we get an alpha release for this branch, please?

**Comment by lefthandedgoat** [comment]
Can't do a release of this branch because too many things are failing.

That being said, I've been staying up late each night and I have a parallel support working both via functions that take a browser instance, and via an object with its own internal browser instance.

You can see what that looks like here: https://github.com/lefthandedgoat/canopy/blob/canopy2/tests/paralleltests/tests1.fs

and here:  https://github.com/lefthandedgoat/canopy/blob/canopy2/tests/paralleltests/tests2.fs

I have a few todos,

- Ensure feature parity for all three modes, classic, function based, instanced based
- Port every test to both function based and instanced based
- Update documentation
- Review all breaking changes and make sure I really want them, backwards compat is 10/10 importance to me.
- After everything is done and working well, add .net core support

I will be putting in hours this weekend to knock out as many of these as I can.  Unfortunately I travel again next week for work, which is exhausting, and I don't know how much effort I can put forth then on anything that is remaining.

**Comment by lefthandedgoat** [comment]
I finished feature parity and have a test suite for both styles which is a port of most of the basic tests.

Function based:
https://github.com/lefthandedgoat/canopy/blob/canopy2/tests/paralleltests/functionsTests.fs

Instance based:
https://github.com/lefthandedgoat/canopy/blob/canopy2/tests/paralleltests/instancedTests.fs

I still need to work on documentation, review all breaking changes, probably use this alpha at work, and finally add .net core support

You can download the alpha package here:
https://www.nuget.org/packages/canopy/2.0.0-alpha

**Comment by amirrajan** [comment]
Aside: I'd say that moving the "old" way to an old namespace is maybe not great (as opposed to creating a "new" `parallel` module).

**Pull request merged**
