### PR TITLE
Paket conversion

### PR DESCRIPTION
**Pull request by forki**
For testing purposes I'm trying to convert canopy.
Maybe you are interested

### CODE REVIEW

**Comment by forki** [comment]
I rebased this PR

**Comment by lefthandedgoat** [comment]
Awesome I understand paket better now so I will accept it soon. Thanks!!

**Comment by forki** [comment]
I noticed that you also use FAKE. Maybe we can convert the whole project
into projectscaffold structure. I can help with that if you are interested.

**Comment by lefthandedgoat** [comment]
Works for me!

**Comment by forki** [comment]
Just took a look. actually it looks pretty close to projectscaffold. so I think this paket transformation will do.

**Comment by sergey-tihon** [comment]
It was aligned with projectscaffold 2 y.o.)

**Pull request merged**
