### PR TITLE
WIP Parallel test runs

### PR DESCRIPTION
**Pull request by haf**

### CODE REVIEW

**Comment by haf** [comment]
@lefthandedgoat Would you mind terribly, enabling travis? I've committed as .travis.yml.

**Comment by lefthandedgoat** [comment]
These changes are in line with what I was thinking.  I think a private 'core' that does all of the real work and exposes functions that take a browser + two public APIs, one that preserves the current API with a global browser, plus one that is object/instance based with a private internal browser that is passed into each core function.

**Comment by haf** [comment]
Yes, that's what I'm adding.

**Comment by lefthandedgoat** [comment]
If I remember correctly I think `coverage` was getting in the way of this.  I am ok with removing it.  I don't think anyone uses it.

https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.fs#L1051

**Comment by haf** [comment]
Can we move the assertions out of the primary assembly? Can they be a separate DLL perhaps? At least they should not be globally available?

**Comment by lefthandedgoat** [comment]
Assertions like `==` ?

**Comment by haf** [comment]
Yes. See e.g. https://github.com/haf/expecto/issues/181 as a discussion topic

**Comment by lefthandedgoat** [comment]
Hm I understand what Ploeh is saying, because in unit testing you can swap out assertion libraries.  The assertions that canopy provides are very specific to UI automation, and provide reliability and other functionality as well.  Off the top of my head it I do feel that the coupling in canopy is ok.  If you feel strong about seperating I can think more on it.

**Comment by haf** [comment]
I don't feel strongly about them being there, but I think they should be optionally exposed and defer to a module, rather than being implemented in the infix operator function declarations. What say you?

**Comment by lefthandedgoat** [comment]
I think having the implementation in a separate module is fine.  For backwards compat and an easy upgrade path the classic api needs to stay, but can be pass through.  I know that people who know F# don't like infixes (for good reason) but it really helps less technical people ramp up.

**Comment by lefthandedgoat** [comment]
Also this will ultimately cause a bump to 2.0 so breaking changes are ok, but I like to keep it to a minimum.

**Comment by haf** [comment]
I'll implement a backwards-compat module with only obsolete functions then that is auto-opened.

WIP here... Could use some help documenting the new browser-based functions. I'm not getting further tonight.

Cheers

**Comment by lefthandedgoat** [comment]
Ok I will work on this some tonight.

**Comment by lefthandedgoat** [comment]
Started helping here: https://github.com/lefthandedgoat/canopy/compare/AddSupportForParallelWithHaf

**Comment by haf** [comment]
Please don't pascal-case the functions and method names :(

**Comment by lefthandedgoat** [comment]
Ok

**Pull request merged**
