### PR TITLE
added param to start chrome at max res

### PR DESCRIPTION
**Pull request by JustinJohnWilliams**
reached out to chromedriver team to try and get a solution to run chrome via the TeamCity service without having to launch the console.exe and explicitly call the agent.bat like we were doing to get a higher res. 

https://code.google.com/p/chromedriver/issues/detail?id=1093&thanks=1093&ts=1431098979

we can change this and add configuration options for desired res if we want, i wanted to try this first and see if it works in TeamCity. I'll run my tests through TC as soon as the NuGet pkg is updated. If it works, then we don't have to use the hack we put in place :)

### CODE REVIEW

**Comment by lefthandedgoat** [comment]
Can you use this? 
https://github.com/lefthandedgoat/canopy/pull/193/files#diff-0c449498f3c369590b1070d415d10d63R674

and you can define your own version of 'chrome'
```
let mychrome =
    let options = OpenQA.Selenium.Chrome.ChromeOptions()
    options.AddArgument("test-type") //https://code.google.com/p/chromedriver/issues/detail?id=799
    options.AddArgument("start-maximized")
    ChromeWithOptions options
```

then use 

```
start mychrome
```

Im not sure that all users will want it to start full screen by default?

**Comment by JustinJohnWilliams** [comment]
Will definitely try, sorry I missed that in the API. checking that in now and our UI tests will run shortly after. will let you know if this fixes it.

**Comment by JustinJohnWilliams** [comment]
seems to have still failed. seems chrome res is still very low. can canopy confirm the res of the browser once the driver has been executed? if that is not available i will ask chromedriver to spit that out... my failures are still the same. I'm assuming this is a chromedriver issue, not canopy!
chromedriver_default_fails

**Comment by lefthandedgoat** [comment]
Can you try setting the res to a manual number, not full screen and see if
it works? Like in their reply?

**Comment by JustinJohnWilliams** [comment]
The way they suggest to set the res manually is on the driver itself, not passing options. Does canopy expose the driver?

**Comment by lefthandedgoat** [comment]
'browser' is the driver

**Comment by amirrajan** [comment]
Should we close this? Now activity for a while.

**Comment by JustinJohnWilliams** [comment]
I see no problem in closing it.

**Pull request closed without merging**
